pipeline {
    agent any
    stages  {
        
        stage("检出") {
            steps {
                checkout(
                    [$class: 'GitSCM', branches: [[name: env.GIT_BUILD_REF]], 
                    userRemoteConfigs: [[url: env.GIT_REPO_URL, credentialsId: env.CREDENTIALS_ID]]]
                )
            }
        }

        stage("构建") {
            steps {
                echo "构建中..."
                // 请在这里放置您项目代码的单元测试调用过程，例如 mvn package
                
                // 演示怎样产生构建物
                script{
                    def exists = fileExists 'README.md'
                    if (!exists) {
                        writeFile(file: 'README.md', text: 'Helloworld')
                    }
                }
                    archiveArtifacts artifacts: 'README.md', fingerprint: true
              
                echo "构建完成."
            }
        }

        stage("测试") {
            steps {
                parallel "单元测试": {
                    echo "单元测试中..."
                    // 请在这里放置您项目代码的单元测试调用过程，例如 mvn test
                    echo "单元测试完成."
                    
                    // 演示怎么样生成测试报告
                    writeFile(file: 'TEST-demo.junit4.AppTest.xml', text: '''
                        <testsuite name="demo.junit4.AppTest" time="0.053" tests="3" errors="0" skipped="0" failures="0">
                            <properties>
                            </properties>
                            <testcase name="testApp" classname="demo.junit4.AppTest" time="0.003"/>
                            <testcase name="test1" classname="demo.junit4.AppTest" time="0"/>
                            <testcase name="test2" classname="demo.junit4.AppTest" time="0"/>
                        </testsuite>
                    ''')
                    junit '*.xml'
                  
                    // 请在这里放置收集单元测试报告的调用过程，JUnit 示例：junit 'target/surefire-reports/*.xml'
                }, "接口测试": {
                    echo "接口测试中..."
                    // 请在这里放置您项目代码的单元测试调用过程，例如 mvn test
                    echo "接口测试完成."
                    // 请在这里放置收集接口测试报告的调用过程，JUnit 示例：junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}